In [1]:
import numpy as np
from matplotlib import pyplot as plt

from polychrom.hdf5_format import list_URIs, load_URI

In [2]:
# First, find the files in the output folder
output_folder = '/mnt/md1/jjusuf/polysim/outputs/trajectory_LEF_EP_absquant_region_bootcamp_version'
files = list_URIs(output_folder)
print(f'{len(files)} saved blocks found')


360000 saved blocks found


In [3]:
# Take a look at the objects in this list: each one represents a saved block
files

['/mnt/md1/jjusuf/polysim/outputs/trajectory_LEF_EP_absquant_region_bootcamp_version/blocks_0-99.h5::0',
 '/mnt/md1/jjusuf/polysim/outputs/trajectory_LEF_EP_absquant_region_bootcamp_version/blocks_0-99.h5::1',
 '/mnt/md1/jjusuf/polysim/outputs/trajectory_LEF_EP_absquant_region_bootcamp_version/blocks_0-99.h5::2',
 '/mnt/md1/jjusuf/polysim/outputs/trajectory_LEF_EP_absquant_region_bootcamp_version/blocks_0-99.h5::3',
 '/mnt/md1/jjusuf/polysim/outputs/trajectory_LEF_EP_absquant_region_bootcamp_version/blocks_0-99.h5::4',
 '/mnt/md1/jjusuf/polysim/outputs/trajectory_LEF_EP_absquant_region_bootcamp_version/blocks_0-99.h5::5',
 '/mnt/md1/jjusuf/polysim/outputs/trajectory_LEF_EP_absquant_region_bootcamp_version/blocks_0-99.h5::6',
 '/mnt/md1/jjusuf/polysim/outputs/trajectory_LEF_EP_absquant_region_bootcamp_version/blocks_0-99.h5::7',
 '/mnt/md1/jjusuf/polysim/outputs/trajectory_LEF_EP_absquant_region_bootcamp_version/blocks_0-99.h5::8',
 '/mnt/md1/jjusuf/polysim/outputs/trajectory_LEF_EP_abs

In [4]:
# We can open one of the files using load_URI
save_block_num = 56711  # the 56,711th saved block
data = load_URI(files[save_block_num])

# The data inside dictionary with the following keys
data.keys()
# only 'SMCs' and 'pos' are important

dict_keys(['SMCs', 'pos', 'block', 'kineticEnergy', 'potentialEnergy', 'time'])

In [5]:
# The 'pos' entry contains the xyz positions of all monomers
# The ith row is monomer i, and the columns represent x,y,z.
# It is an Nx3 numpy array
print(data['pos'])


[[ -6.077  10.363  -7.298]
 [ -5.328  10.14   -7.987]
 [ -4.389  10.626  -8.05 ]
 ...
 [ -3.865 -16.221  -4.126]
 [ -4.766 -16.142  -4.35 ]
 [ -4.394 -16.575  -5.356]]


In [6]:
# The 'SMCs' entry shows you the locations of the cohesins (aka LEFs)
# Each row represents the [left_pos, right_pos] of a cohesin
# It is not in any particular order
data['SMCs']


array([[22828, 23056],
       [17935, 18285],
       [50724, 50866],
       [43991, 44199],
       [61147, 61269],
       [34724, 35241],
       [46043, 46428],
       [48159, 48339],
       [30330, 30829],
       [    1,   199],
       [16200, 16694],
       [18449, 18694],
       [ 5753,  5845],
       [44201, 44323],
       [54724, 55390],
       [27753, 28199],
       [ 5754,  5844],
       [65242, 65580],
       [17936, 17998],
       [49436, 49785],
       [69426, 69580],
       [48096, 48340],
       [43391, 43507],
       [44472, 44574],
       [ 7433,  7603],
       [  200,   694],
       [18886, 18911],
       [54012, 54574],
       [38758, 39180],
       [ 3214,  3390],
       [41783, 41991],
       [12507, 12569],
       [44724, 45103],
       [ 5089,  5159],
       [11360, 11491],
       [37433, 37580],
       [34957, 35025],
       [23057, 23434],
       [43698, 43716],
       [35447, 35520],
       [48724, 49233],
       [40292, 40327],
       [ 9949, 10204],
       [487