# Visualization

This notebook shows you how to visualize a polymer conformation in an iPython notebook (VSCode/Jupyter) using the `py3Dmol` package.

In [2]:
# setup
import numpy as np
import py3Dmol  # for visualizing the polymer
from polychrom.hdf5_format import list_URIs, load_URI  # for opening simulation output files


## Load the data

In [2]:
# First, use `list_URIs` to create a list of the file paths of the saved blocks:

output_folder = '/mnt/md1/jjusuf/polysim/outputs/trajectory0003_npoly70000_nchr1_dens0.3_life75000_sep240_vlef0.0025_dt40_stallsites0.05-0.6_lifeboost4_ntypes2'
files = list_URIs(output_folder)

print(f'{len(files)} saved blocks found')


360000 saved blocks found


In [3]:
# Then, open one of the conformations

save_block_num = 56711
uri = load_URI(files[save_block_num])
xyz = uri['pos']

print(xyz)
print(f'shape: {xyz.shape}')

# It is an (N, 3) array of xyz positions of all N monomers


[[ -6.077  10.363  -7.298]
 [ -5.328  10.14   -7.987]
 [ -4.389  10.626  -8.05 ]
 ...
 [ -3.865 -16.221  -4.126]
 [ -4.766 -16.142  -4.35 ]
 [ -4.394 -16.575  -5.356]]
shape: (70000, 3)


## Visualize the polymer

In [4]:
# Take a subset of the polymer (first 1000 monomers)
xyz_subset = xyz[:1000,:]


In [5]:
# Sphere model
# Here we draw a sphere for each monomer

view = py3Dmol.view()

for i in range(len(xyz_subset)):
    pos = xyz_subset[i,:]
    view.addSphere({
        "center": {"x": float(pos[0]), "y": float(pos[1]), "z": float(pos[2])},
        "radius": 0.5,
        "color": "#dddddd"
    })

view.setBackgroundColor('white')
view.zoomTo()
view.show()


3Dmol.js failed to load for some reason. Please check your browser console for error messages.

In [6]:
# Stick model
# Here we draw sticks between every pair of adjacent monomers

view = py3Dmol.view()

for i in range(len(xyz_subset)-1):
    pos1 = xyz_subset[i,:]
    pos2 = xyz_subset[i+1,:]
    view.addCylinder({
        "start": {"x": float(pos1[0]), "y": float(pos1[1]), "z": float(pos1[2])},
        "end":   {"x": float(pos2[0]), "y": float(pos2[1]), "z": float(pos2[2])},
        "radius": 0.4,
        "fromCap": 2, "toCap": 2,
        "color": "#dddddd"
    })

view.setBackgroundColor('white')
view.zoomTo()
view.show()


3Dmol.js failed to load for some reason. Please check your browser console for error messages.

## Advanced

In [7]:
# Take a subset of the polymer, but now keep track of the indices
pos_start = 8000
pos_end   = 9000

xyz_subset = xyz[pos_start:pos_end, :]
indices = np.arange(pos_start, pos_end)


In [8]:
# Now make a sphere model but give some monomers different colors

sticky_monomers = [250, 372, 540, 745, 775, 833, 961, 1202, 1330, 1640, 1722]  # in the first repeat
ctcf_sites = [ 200,  330,  574,  694,  724,  866, 1241, 1390, 1425, 1433, 1580, 1604, 1752, 1800]  # in the first repeat
region_size = 2000

view = py3Dmol.view()

for i in range(len(xyz_subset)):
    pos = xyz_subset[i,:]
    monomer_index = indices[i]

    if (monomer_index % region_size) in sticky_monomers:
        color = "#1eabec"
        alpha = 1
    elif (monomer_index % region_size) in ctcf_sites:
        color = "#c71a34"
        alpha = 1
    else:
        color = "#dddddd"  # default color
        alpha = 0.75         # make them translucent

    view.addSphere({
        "center": {"x": float(pos[0]), "y": float(pos[1]), "z": float(pos[2])},
        "radius": 0.5,
        "color": color,
        "alpha": alpha
    })

view.setBackgroundColor('white')
view.zoomTo()
view.show()


3Dmol.js failed to load for some reason. Please check your browser console for error messages.